enableStrictSsl: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0032
    level: discard
  - code: YN0060
    level: discard
  - code: YN0061
    level: discard
  - code: YN0062
    level: discard
  - code: YN0076
    level: discard
  - code: YN0018
    level: discard

nodeLinker: node-modules

npmPublishRegistry: "https://registry.npmjs.org/"

npmRegistryServer: "https://registry.npmmirror.com/"

npmScopes:
  hulujs:
    npmPublishRegistry: "https://registry.npmjs.org/"
    npmRegistryServer: "https://registry.npmjs.org/"
  my-org:
    npmAlwaysAuth: true

yarnPath: .yarn/releases/yarn-4.2.2.cjs
